### ISSUE TITLE
Not signing into Firebase - something wrong with redirectUrl?

### ISSUE THREAD

**Issue by js1972** [Kunstmaan/flutter_slack_oauth_firebase#2]
Hi am trying to test out your plugin here and get the example provided to work but can't. The app just hangs on the webview showing the url: "https://kunstmaan.github.io/flutter_slack_oauth/success.html".

Because the *tokenReceived* callback (from jsonp in the token function) redirects to the above kuntsmaan.github.io success page; the webview *onUrlChanged()* handler never finds a path starting with the provided redirectUrl - which in your example code is given as "https://<project>.firebaseapp.com/completed.html".

If however I change your code such that the tokenReceived function in index.html instead does this:
```
window.location.href = "https://<project>.firebaseapp.com/completed.html?customToken=" + data.token;
```
to match the redirectUrl - then the webviews onUrlChanged handler does match the redirectUrl and the code goes on to call:
```
FirebaseUser user =
              await _auth.signInWithCustomToken(token: customToken);
```
But this fails with an error stating that its an invalid firebase token...

Just wondering if this is still working for you. I've been debugging for quite some time but just seem to be struggling and going in circles.  ;-)

ps. All the other parts of the code like the firebase functions seem to be working fine based on their log output and the database is populated with the user data...
The token cloud function log states that a firebase token has been successfully created as well...

**Comment by js1972** [comment]
I've resolved the specific issue above. Firstly you do need to change the token cloud function to redirect to a matching html file that you specified in your flutter app as the redirect url. Secondly it turns out that the errors I was getting when signing into Firebase with the custom token where because of a Firebase bug where the iOS plist file is missing the API_KEY value from your Firebase project. You can manually add this value or simply re-export the plist from Firebase and it will have it. See https://stackoverflow.com/questions/37436352/invalid-api-key-supplied-using-firebase.

Still got a bit of work though - need to work out how to use refresh tokens and so on with this approach which doesn't seem to be supported with this plugin.

**Comment by thomas-stockx** [comment]
Hi,

Glad you got it working (apologies for the late response, I was on holiday without access to a decent laptop).

You're right, there's an bug that was fixed in our production code that didn't make it into the repo. Your change to the tokenReceived method is indeed what we also have in our production code, so I'll update the repo accordingly.

We don't use refresh tokens because our use case doesn't require them, but you're always welcome to open a pull request!

**Comment by js1972** [comment]
Thanks for getting back..... after chatting to a few other people about this topic we won’t be using re-use tokens with azure ad either. Once authenticated we just let firebase take over from there and it seems to be working well...
The only concern I have in general with this technique is the firebase functions can be called by anyone and therefore rack up billing charges... it might be an unfounded concern but I guess it does mean you need to be monitoring them and looking for usage spikes so they can be shutdown/changed if need be....
